import type { ReadingStyle, StyleId } from './types'

const CODE_FONT_STACK = "'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', monospace"

export const PRESETS: Record<StyleId, ReadingStyle> = {
  book: {
    id: 'book',
    name: '书籍',
    palette: {
      background: '#FAF7F0',
      text: '#2C2523',
      muted: '#7C7267',
      accent: '#8B4513',
      rule: '#E5DFD3',
      codeBackground: '#F0EAE1',
    },
    body: {
      fontStack: "'Georgia', 'Iowan Old Style', 'Charter', serif",
      fontSizePx: 19,
      lineHeight: 1.62,
      measureCh: 66,
      align: 'justify',
      hyphens: true,
      paragraph: 'indent',
    },
    elements: {
      headingFontStack: "'Georgia', 'Iowan Old Style', 'Charter', serif",
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'indent',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  sepia: {
    id: 'sepia',
    name: '羊皮纸',
    palette: {
      background: '#F4ECD8',
      text: '#382C1E',
      muted: '#7D6F5D',
      accent: '#7B3F00',
      rule: '#DED4BC',
      codeBackground: '#EAE0C8',
    },
    body: {
      fontStack: "'Georgia', 'Iowan Old Style', 'Charter', serif",
      fontSizePx: 19,
      lineHeight: 1.62,
      measureCh: 66,
      align: 'justify',
      hyphens: true,
      paragraph: 'indent',
    },
    elements: {
      headingFontStack: "'Georgia', 'Iowan Old Style', 'Charter', serif",
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'indent',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  night: {
    id: 'night',
    name: '夜读',
    palette: {
      background: '#1C1C1E',
      text: '#D1D1D6',
      muted: '#8E8E93',
      accent: '#D4A373',
      rule: '#38383A',
      codeBackground: '#2C2C2E',
    },
    body: {
      fontStack: "'Georgia', 'Iowan Old Style', 'Charter', serif",
      fontSizePx: 19,
      lineHeight: 1.68,
      measureCh: 66,
      align: 'start',
      hyphens: false,
      paragraph: 'spaced',
    },
    elements: {
      headingFontStack: "'Georgia', 'Iowan Old Style', 'Charter', serif",
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'indent',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  journal: {
    id: 'journal',
    name: '科学杂志',
    palette: {
      background: '#FBFBFA',
      text: '#1E2022',
      muted: '#686E74',
      accent: '#1D4ED8',
      rule: '#E2E4E8',
      codeBackground: '#F1F3F5',
    },
    body: {
      fontStack: "'Palatino', 'Palatino Linotype', 'Iowan Old Style', 'Georgia', serif",
      fontSizePx: 18,
      lineHeight: 1.75,
      measureCh: 62,
      align: 'start',
      hyphens: false,
      paragraph: 'spaced',
    },
    elements: {
      headingFontStack: "'system-ui', -apple-system, sans-serif",
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 700,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'rule',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  news: {
    id: 'news',
    name: '报刊',
    palette: {
      background: '#F9F9F8',
      text: '#111111',
      muted: '#555555',
      accent: '#B91C1C',
      rule: '#CCCCCC',
      codeBackground: '#EBEBEB',
    },
    body: {
      fontStack: "'Charter', 'Bitstream Charter', 'Georgia', serif",
      fontSizePx: 17,
      lineHeight: 1.45,
      measureCh: 72,
      align: 'justify',
      hyphens: true,
      paragraph: 'indent',
    },
    elements: {
      headingFontStack: "'Charter', 'Georgia', serif",
      headingScale: [2.0, 1.6, 1.35, 1.2, 1.1, 1.0],
      headingWeight: 700,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'rule',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  song: {
    id: 'song',
    name: '中文宋体',
    palette: {
      background: '#FAF7F2',
      text: '#2B2B2B',
      muted: '#787878',
      accent: '#8C2D19',
      rule: '#E0DAD0',
      codeBackground: '#EEE8DF',
    },
    body: {
      fontStack: "'Georgia', 'Songti SC', 'STSong', 'Noto Serif CJK SC', 'Source Han Serif SC', serif",
      fontSizePx: 18,
      lineHeight: 1.80,
      measureCh: 40,
      align: 'justify',
      hyphens: false,
      paragraph: 'indent',
      isCjk: true,
    },
    elements: {
      headingFontStack: "'Georgia', 'Songti SC', 'STSong', 'Noto Serif CJK SC', serif",
      headingScale: [1.75, 1.45, 1.25, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'rule',
      listIndentEm: 2.0,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
}
