import type { ReadingStyle, StyleId } from './types'

const CODE_FONT_STACK = "'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', monospace"
const APPLE_SERIF =
  '-apple-system-ui-serif, "New York", "Iowan Old Style", "Charter", "Georgia", serif'
const APPLE_SANS =
  '-apple-system, "SF Pro Text", "SF Pro", "Helvetica Neue", Arial, sans-serif'
const APPLE_SONG =
  '-apple-system-ui-serif, "Songti SC", "STSong", "Noto Serif CJK SC", "Source Han Serif SC", serif'

export const PRESETS: Record<StyleId, ReadingStyle> = {
  book: {
    id: 'book',
    name: '书籍',
    palette: {
      background: '#F9F6F0',
      text: '#24211E',
      muted: '#78716A',
      accent: '#9A3412',
      rule: '#E7E2D8',
      codeBackground: '#EFEAE0',
    },
    body: {
      fontStack: APPLE_SERIF,
      fontSizePx: 19,
      lineHeight: 1.68,
      measureCh: 66,
      align: 'justify',
      hyphens: true,
      paragraph: 'indent',
    },
    elements: {
      headingFontStack: APPLE_SERIF,
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'indent',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  sepia: {
    id: 'sepia',
    name: '羊皮纸',
    palette: {
      background: '#F4ECD8',
      text: '#36291C',
      muted: '#7B6E5E',
      accent: '#854D0E',
      rule: '#DFD3B9',
      codeBackground: '#E8DCBF',
    },
    body: {
      fontStack: APPLE_SERIF,
      fontSizePx: 19,
      lineHeight: 1.68,
      measureCh: 66,
      align: 'justify',
      hyphens: true,
      paragraph: 'indent',
    },
    elements: {
      headingFontStack: APPLE_SERIF,
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'indent',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  night: {
    id: 'night',
    name: '夜读',
    palette: {
      background: '#161618',
      text: '#D6D6DA',
      muted: '#8E8E93',
      accent: '#E2B887',
      rule: '#2C2C30',
      codeBackground: '#242428',
    },
    body: {
      fontStack: APPLE_SERIF,
      fontSizePx: 19,
      lineHeight: 1.72,
      measureCh: 66,
      align: 'start',
      hyphens: false,
      paragraph: 'spaced',
    },
    elements: {
      headingFontStack: APPLE_SERIF,
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'indent',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  journal: {
    id: 'journal',
    name: '科学杂志',
    palette: {
      background: '#FBFBFA',
      text: '#181A1C',
      muted: '#646A72',
      accent: '#2563EB',
      rule: '#E2E5E9',
      codeBackground: '#F0F2F5',
    },
    body: {
      fontStack: '"Palatino", "Palatino Linotype", "Iowan Old Style", ' + APPLE_SERIF,
      fontSizePx: 18,
      lineHeight: 1.75,
      measureCh: 62,
      align: 'start',
      hyphens: false,
      paragraph: 'spaced',
    },
    elements: {
      headingFontStack: APPLE_SANS,
      headingScale: [1.8, 1.5, 1.3, 1.15, 1.05, 1.0],
      headingWeight: 700,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'rule',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  news: {
    id: 'news',
    name: '报刊',
    palette: {
      background: '#F6F6F5',
      text: '#111111',
      muted: '#5C5C5C',
      accent: '#DC2626',
      rule: '#D4D4D4',
      codeBackground: '#E8E8E8',
    },
    body: {
      fontStack: '"Charter", "Bitstream Charter", ' + APPLE_SERIF,
      fontSizePx: 17,
      lineHeight: 1.52,
      measureCh: 72,
      align: 'justify',
      hyphens: true,
      paragraph: 'indent',
    },
    elements: {
      headingFontStack: '"Charter", ' + APPLE_SERIF,
      headingScale: [2.0, 1.6, 1.35, 1.2, 1.1, 1.0],
      headingWeight: 700,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'rule',
      listIndentEm: 1.5,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
  song: {
    id: 'song',
    name: '中文宋体',
    palette: {
      background: '#FAF6EE',
      text: '#242220',
      muted: '#757068',
      accent: '#991B1B',
      rule: '#E2DCD0',
      codeBackground: '#EFE8DC',
    },
    body: {
      fontStack: APPLE_SONG,
      fontSizePx: 18,
      lineHeight: 1.85,
      measureCh: 40,
      align: 'justify',
      hyphens: false,
      paragraph: 'indent',
      isCjk: true,
    },
    elements: {
      headingFontStack: APPLE_SONG,
      headingScale: [1.75, 1.45, 1.25, 1.15, 1.05, 1.0],
      headingWeight: 600,
      codeFontStack: CODE_FONT_STACK,
      blockquote: 'rule',
      listIndentEm: 2.0,
      tableBorder: 'horizontal',
      figureCaptionScale: 0.85,
    },
  },
}
